### ISSUE TITLE
[PROJECT IDEA] Create a registry API backup, by scraping and serving the existing API

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iati-ideas#15]
I _think_ this was the idea @markbrough proposed on the codeforIATI call.

Did I get this right, @markbrough?

**Comment by andylolz** [comment]
On discord, @notshi said:

> That would be nice if the Registry is just a single file that you can download because it's a small enough amount of data that it should be!

I’ve had a go at implementing that here: https://registry.codeforiati.org

**Comment by notshi** [comment]
Thanks, @andylolz - I meant the Registry could be replaced, not just mirrored :}

We've been grabbing this data and it's in git so there's a history attached to it, if you're interested.

https://github.com/devinit/D-Portal/blob/master/dstore/json/publishers.json
https://github.com/devinit/D-Portal/blob/master/dstore/json/packages.json

**Comment by andylolz** [comment]
Ha! I should have known d-portal would have already done it, years ago! :)

I think I did know that you already make this available, but completely forgot I’m afraid.

Okay, so… https://registry.codeforiati.org is duplicative of that effort, but I think I’ll leave it running anyway, because:
 * It uses a slightly different format, that **is less useful**, but more closely mirrors the registry API format
 * It updates more frequently
 * The URLs are a bit friendlier, and it has its own mini website

I’m clutching at straws a bit!

**Comment by notshi** [comment]
We really don't have a problem with duplicative efforts - that's why the internet stays up :}
We are unsure why this is seen as a bad thing.

You can still provide a service for the publishers but it could be in a known IATI format, at the very least.
The CKAN has its own standard, separate from IATI (why?!) and the API is also frustratingly slow.
This doesn't help new users coming in cold.
